[versions]
kotlin = "2.1.20"

minecraft = "1.21.5"

fabric-loom = "1.10-SNAPSHOT"

paper = "1.21.5-R0.1-SNAPSHOT"

yarn = "1.21.5+build.1"

yacla-core = "1.1.0+beta.1"
yacla-yaml = "1.1.0+beta.1"
yacla-json = "1.1.0+beta.1"
yacla-ext-db = "1.1.0+beta.1"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }

[libraries]
paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }

minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }

yarn = { group = "net.fabricmc", name = "yarn", version.ref = "yarn" }

yacla-core = { group = "net.ririfa", name = "yacla-core", version.ref = "yacla-core" }
yacla-yaml = { group = "net.ririfa", name = "yacla-yaml", version.ref = "yacla-yaml" }
yacla-json = { group = "net.ririfa", name = "yacla-json", version.ref = "yacla-json" }
yacla-ext-db = { group = "net.ririfa", name = "yacla-ext-db", version.ref = "yacla-ext-db" }