[versions]
kotlin = "2.2.21"
fabric-loom = "1.13-SNAPSHOT"
shadow = "9.2.2"

minecraft = "1.21.10"
yarn = "1.21.10+build.2"
paper = "1.21.10-R0.1-SNAPSHOT"

yacla-core = "3.0.0"
yacla-yaml = "3.0.0"
yacla-json = "3.0.0"

langMan-core = "2.0.0"
langMan-yaml = "2.0.0"

cask = "1.0.0"

beacon = "1.5.4"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }

[libraries]
paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }

minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }

yarn = { group = "net.fabricmc", name = "yarn", version.ref = "yarn" }

yacla-core = { group = "net.ririfa", name = "yacla-core", version.ref = "yacla-core" }
yacla-yaml = { group = "net.ririfa", name = "yacla-yaml", version.ref = "yacla-yaml" }
yacla-json = { group = "net.ririfa", name = "yacla-json", version.ref = "yacla-json" }
langman-core = { group = "net.ririfa", name = "langman-core", version.ref = "langMan-core" }
langman-yaml = { group = "net.ririfa", name = "langman-ext.yaml", version.ref = "langMan-yaml" }
cask = { group = "net.ririfa", name = "cask", version.ref = "cask" }
beacon = { group = "net.ririfa", name = "beacon", version.ref = "beacon" }
